name: Go Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Tests and Coverage
        run: go test ./... -coverprofile=coverage && go tool cover -func=coverage